
# HW1

## Course 1: Introduction to R

### 次方
```{r comment='' }
2**4
2^4 #**和^皆可以表示次方
```
### 指定變數值
```{r comment=''}
x<-8
x
x=8   # =, <-都可以
x
```
### 創建向量（裡面元素可以是四種type，但所有元素須為同種）
```{r comment=''}
myvec1=c(T,T,F,F)
typeof(myvec1)   #同為邏輯值logical
myvec2=1:5
typeof(myvec2)   #同為整數integer
myvec3=c(2.8,4.7,50.3)
typeof(myvec3)   #同為數值numeric
myvec4=c('cat','rabbit','hamster')
typeof(myvec4)   #同為字串character
```
### 以邏輯運算子選取向量元素
```{r comment=''}
x<-c(14,21,13,9,28,38,45)
a=x%%4==1
a    #a是一連串邏輯判斷
x[a]   #x[a]把是T的選出來
```
### 創建矩陣及合併為矩陣（與向量同，所有元素須為同種）
```{r comment=''}
m=matrix(1:48, byrow=T , nrow= 12)
m
a=c(7,16,59)
b=c(25,30,41)
cbind(a,b)  #以「行」結合
rbind(a,b)  #以「列」結合
```
### 創建因子factor（一種特殊的向量形式，首先要有向量才可產生）
```{r comment=''}
c=c('world','continent','country')
factor(c)#沒有等級大小之分的nominal categorical variable，不可以比較大小
#有等級大小之分的ordinal categorical variable，可以比較大小
factor(c,ordered=T,levels=c('country','continent','world')) 
```
### Dataframe（為解決矩陣的不足，裡面的元素可以是不同種類的）
```{r comment=''}
a=c(1,2,3,4,5)
b=c('Asia',"Africa","America","Europe","Oceania")
c=c(T,T,T,F,T)
data.frame(id = a, cont =b,desert=c) ##注意，每個向量要一樣項數
```
### Dataframe的選取
```{r comment=''}

d=data.frame(id = a, cont =b,desert=c)
d[3:4,] #3,4列
d[4,3] #第4列第3行
d[,3]  #第3行全
```
### List（可以儲存各種資料，除了4種變數type，也可以存向量、矩陣、Dataframe、List）
```{r comment=''}
a=7 
b='good'
c=F
d=c(8,9,10)
e=matrix(1:9, byrow=T , nrow= 3)
f=data.frame('1'=c('a','b','c'), '2'=c(100,300,500))
li=list(a,b,c,d,e,f) #創建
li  #數值+字串+邏輯值+向量+矩陣+Dataframe
```
### 命名List裡面的元素
```{r comment=''}
li=list('numeric'=a,'character'=b,'logical'=c,'vector'=d,'matrix'=e,'dataframe'=f)
li
```
### 選取List裡面的元素（以index選）
```{r comment=''}
li[[4]]       ##注意：一定要以[[]]的形式，才能表示list的項
li[[6]][3,2]  ##後來的[]是針對已選取此項裡面的元素
```
### 查詢函數str()可以查詢基本的資料
```{r comment=''}
str(li)
```