source('pttTestFunction.R')
id = c(1165:1169)
URL = paste0("https://www.ptt.cc/bbs/fastfood/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)

rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))
#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
docs <- tm_map(docs, toSpace, "推")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace, "了")
docs <- tm_map(docs, toSpace, "不")
docs <- tm_map(docs, toSpace, "都")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "換")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "稅後")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace, "有")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "會")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "大")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "比較")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "買")
docs <- tm_map(docs, toSpace, "嗎")
docs <- tm_map(docs, toSpace, "啊")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace, "很")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "或")
docs <- tm_map(docs, toSpace, "元")
docs <- tm_map(docs, toSpace, "送")
docs <- tm_map(docs, toSpace, "一")
docs <- tm_map(docs, toSpace, "今天")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "徵")
docs <- tm_map(docs, toSpace, "用")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "想")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "樣")
docs <- tm_map(docs, toSpace, "能")
docs <- tm_map(docs, toSpace, "點")
docs <- tm_map(docs, toSpace, "過")
docs <- tm_map(docs, toSpace, "店員")
#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
docs

mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")

wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=50,max.words=150,
          random.order=F, random.color=FALSE, 
          rot.per=.1, colors=brewer.pal(8, "Dark2"),
          ordered.colors=F,use.r.layout=FALSE,
          fixed.asp=TRUE)
