---
title: "Report of Interactive maps and EDA of gun violence in the US"
---
### 載入一些跟繪圖有關的套件
```{r  message=FALSE, warning=FALSE, comment=''}
# setup
knitr::opts_chunk$set(message=FALSE, fig.height=3, fig.width=5)
library(ggplot2) # to make pretty plots
library(dplyr) # for inner_join and left_join
library(car) # to recode
library(maps) # for the maps
library(gridExtra) # to arrange the plots in grids
library(plotly) # for interactive plots
library(cowplot) # to have get_legent
```

### 匯入csv資料以及檢視一下資訊，總共有三個檔案，分別代表2015、2016、2017三個年度
```{r  message=FALSE, warning=FALSE, comment=''}
happy_2015 <- read.csv("2015.csv")
happy_2016 <- read.csv("2016.csv")
happy_2017 <- read.csv("2017.csv")
str(happy_2015)
str(happy_2016)
str(happy_2017)
```

### 因到時會把三個dataframe整合成一個dataframe，所以重新命名三個年度的column名稱以利辨別
### 一樣的欄位名稱要標上年份表示不同年度
```{r  message=FALSE, warning=FALSE, comment=''}
colnames(happy_2015) <- c("Country","Region","Rank_2015","Score_2015","Err_2015","GDP_2015","Family_2015","Health_2015","Freedom_2015","Gov_2015","Generosity_2015","Dist_res_2015")
colnames(happy_2016) <- c("Country","Region_2016","Rank_2016","Score_2016","LCI_2016","UCI_2016","GDP_2016","Family_2016","Health_2016","Freedom_2016","Gov_2016","Generosity_2016","Dist_res_2016")
colnames(happy_2017) <- c("Country","Rank_2017","Score_2017","Whisker.high_2016","Whisker.low_2017","GDP_2017","Family_2017","Health_2017","Freedom_2017","Generosity_2017","Gov_2017","Dist_res_2017")
```

### 利用merge函數，接合三個dataframe成新的一個
```{r  message=FALSE, warning=FALSE, comment=''}
happy <- merge(happy_2015, happy_2016, by.x = "Country", by.y = "Country")
happy <- merge(happy, happy_2017, by.x = "Country", by.y = "Country")
happy$Region_2016 <- NULL
str(happy)  
```

### 更改一些國家名字
```{r  message=FALSE, warning=FALSE, comment=''}
happy$Country <- recode(happy$Country, 
                        "'Congo (Brazzaville)' = 'Democratic Republic of the Congo';
                        'Congo (Kinshasa)'='Republic of Congo';
                        'United States'='USA';
                        'United Kingdom'= 'UK'
                        ")
```

```{r  message=FALSE, warning=FALSE, comment=''}
happy[,1]=as.character(happy[,1])
```
